version: "3.8"

services:
  fastapi:
    build: .
    container_name: diller-service-api
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    networks:
      - shared_network
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

networks:
  shared_network:
    external: true